[package]
name = "turnstile"
version = "0.1.0"
authors = ["Brenden Matthews <brenden@brndn.io>"]
edition = "2018"

[dependencies]
env_logger = { version = "0.5", default-features = false }
failure = "0.1"
futures = "0.1"
http = "0.1"
instrumented = { git = "ssh://git@github.com/umpyre-code/instrumented.git" }
lazy_static = "1.3"
log = "0.4"
rocket = "0.4.0"
rocket_cors = "0.4.0"
rolodex-grpc = { git = "ssh://git@github.com/umpyre-code/rolodex.git" }
rustls = "0.15"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
syn = "0.15" # 0.15.32 fails to compile
tokio = "0.1"
tokio-connect = { git = "https://github.com/carllerche/tokio-connect" }
tokio-rustls = "0.9"
toml = "0.5"
tower = { git = "https://github.com/tower-rs/tower" }
tower-buffer = { git = "https://github.com/tower-rs/tower" }
tower-grpc = { git = "https://github.com/tower-rs/tower-grpc" }
tower-h2 = { git = "https://github.com/tower-rs/tower-h2" }
tower-http = { git = "https://github.com/tower-rs/tower-http" }
tower-request-modifier = { git = "https://github.com/tower-rs/tower-http" }
webpki = "0.19"
yansi = "0.5"

[patch.crates-io]
cookie = { git = "https://github.com/alexcrichton/cookie-rs.git"}

[dependencies.rocket_contrib]
version = "0.4.0"
default-features = false
features = ["json"]
