[service]
site_uri = "http://localhost:8000"
enable_hsts = false

[rolodex]
tls_cert_path = "tests/certs/Frontend.crt"
tls_key_path = "tests/certs/Frontend.key"
ca_cert_path = "tests/certs/UmpyreAuth.crt"
host = "localhost"
port = 10011

[switchroom]
tls_cert_path = "tests/certs/Frontend.crt"
tls_key_path = "tests/certs/Frontend.key"
ca_cert_path = "tests/certs/UmpyreAuth.crt"
host = "localhost"
port = 10012

[jwt]
iss = "Umpyre"
exp = 10000000000
jwt_secret = "secretsecretsecret"
# To generate:
#   $ openssl rand -base64 32
encryption_secret = "6BGlVqPAQH2/RFNSGrmGdbiFVt/lWHVfyXX5cSyFmKc="

[metrics]
bind_to_address = "127.0.0.1:5000"

[rate_limits.public]
# number of requests per period
tokens = 100
# period (in seconds) for requests / period
period = 10
# maximum burst
max_burst = 100

[rate_limits.private]
# number of requests per period
tokens = 100
# period (in seconds) for requests / period
period = 10
# maximum burst
max_burst = 100
