site_uri = "http://localhost:8000"
worker_threads = 4

[rolodex]
tls_cert_path = "test/Rolodex.crt"
tls_key_path = "test/Rolodex.key"
ca_cert_path = "test/UmpyreAuth.crt"
host = "localhost"
port = 10011
